### ISSUE TITLE
[CTD] Cannot set property PropertyInteger, like #115

### ISSUE THREAD

**Issue by drakray** [Daveyx0/PrimitiveMobs#150]
https://pastebin.com/qbVZsWNW

Looking a lot like #115, Crashed To Desktop when walking

```
java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} to 16 on block actuallyadditions:block_rice, it is not an allowed value
	at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:59)
	at net.minecraft.block.BlockCrops.func_185528_e(BlockCrops.java:61)
	at net.minecraft.block.BlockCrops.func_176203_a(BlockCrops.java:251)
	at net.daveyx0.primitivemobs.entity.passive.EntityGroveSprite$AIManageSaplings.shouldMoveToSapling(EntityGroveSprite.java:718)
	at net.daveyx0.primitivemobs.entity.passive.EntityGroveSprite$AIManageSaplings.searchForDestination(EntityGroveSprite.java:683)
	at net.daveyx0.primitivemobs.entity.passive.EntityGroveSprite$AIManageSaplings.func_75250_a(EntityGroveSprite.java:605)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.daveyx0.primitivemobs.entity.passive.EntityGroveSprite.func_70071_h_(EntityGroveSprite.java:208)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by drakray** [comment]
MC 1.12.2
Forge 2796
MultiMob 1.0
PrimitiveMobs 1.1.6
BunchaOthers

**Comment by Daveyx0** [comment]
SHould be fixed next update :)
