### ISSUE TITLE
Crashes with latest update

### ISSUE THREAD

**Issue by MohawkyMagoo** [Daveyx0/PrimitiveMobs#214]
Time: 1/23/19 12:23 AM
Description: Exception ticking world

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at net.daveyx0.multimob.spawn.MMSpawnChecks.isLuckyEnoughToSpawn(MMSpawnChecks.java:180)
	at net.daveyx0.multimob.spawn.MMSpawnChecks.performSpawnChecks(MMSpawnChecks.java:38)
	at net.daveyx0.multimob.spawn.MMSpawnerEventHandler.onCheckSpawn(MMSpawnerEventHandler.java:61)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_586_MMSpawnerEventHandler_onCheckSpawn_CheckSpawn.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:201)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:151)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Random.nextInt(Unknown Source)
	at net.daveyx0.multimob.spawn.MMSpawnChecks.isLuckyEnoughToSpawn(MMSpawnChecks.java:180)
	at net.daveyx0.multimob.spawn.MMSpawnChecks.performSpawnChecks(MMSpawnChecks.java:38)
	at net.daveyx0.multimob.spawn.MMSpawnerEventHandler.onCheckSpawn(MMSpawnerEventHandler.java:61)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_586_MMSpawnerEventHandler_onCheckSpawn_CheckSpawn.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:201)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:151)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)

**Comment by MohawkyMagoo** [comment]
It seems to be if I make changes to the configs to disable mobs - it crashes - if I let the configs regen and leave them alone - it doesnt crash.  It looks like there is some kind of conflict between the PM Mobs config and the Multimob config?

**Comment by Daveyx0** [comment]
Thanks! Will check it out after work. Is this with the new Multimob hotfix?

**Comment by MohawkyMagoo** [comment]
yes, all latest versions

**Comment by BugmanBugman** [comment]
have we gotten an update to this davey?
