### ISSUE TITLE
Client Side Crash With Dedicated Server (multimob-1.0.4a, primitivemobs-1.2.3a)

### ISSUE THREAD

**Issue by SteveKnowless** [Daveyx0/PrimitiveMobs#219]
multimob-1.0.4a
primitivemobs-1.2.3a

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2019-01-26 13:45:49 EST
Description: Ticking entity

java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Integer
    at net.daveyx0.primitivemobs.entity.monster.EntityBabySpider.getGrowthLevel(EntityBabySpider.java:196)
    at net.daveyx0.primitivemobs.entity.monster.EntityBabySpider.canBeSteered(EntityBabySpider.java:84)
    at net.minecraft.entity.EntityLiving.canPassengerSteer(EntityLiving.java:1601)
    at net.minecraft.entity.EntityLivingBase.travel(EntityLivingBase.java:1839)
    at net.daveyx0.primitivemobs.entity.monster.EntityBabySpider.travel(EntityBabySpider.java:376)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2393)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678)
    at net.minecraft.entity.monster.EntityMob.onLivingUpdate(EntityMob.java:45)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50)
    at net.daveyx0.primitivemobs.entity.monster.EntityPrimitiveSpider.onUpdate(EntityPrimitiveSpider.java:79)
    at net.daveyx0.primitivemobs.entity.monster.EntityBabySpider.onUpdate(EntityBabySpider.java:153)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zbl000(World.java:5117)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at pl.skmedix.loader.GameLoader.main(GameLoader.java:35)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: primitivemobs:baby_spider (net.daveyx0.primitivemobs.entity.monster.EntityBabySpider)
  Entity ID: 10608
  Entity Name: Baby Spider
  Entity's Exact location: 329.33, 18.00, 216.25
  Entity's Block location: World: (329,18,216), Chunk: (at 9,1,8 in 20,13; contains blocks 320,0,208 to 335,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: ~~ERROR~~ ReportedException: Saving entity NBT

**Comment by SteveKnowless** [comment]
Also get this one

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2019-01-26 14:41:17 EST
Description: Ticking entity

java.lang.ClassCastException: com.google.common.base.Present cannot be cast to java.lang.Integer
    at net.daveyx0.primitivemobs.entity.passive.EntityGroveSprite.getSaplingTimer(EntityGroveSprite.java:525)
    at net.daveyx0.primitivemobs.entity.passive.EntityGroveSprite.onUpdate(EntityGroveSprite.java:202)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zbl000(World.java:5117)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at pl.skmedix.loader.GameLoader.main(GameLoader.java:35)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: primitivemobs:grovesprite (net.daveyx0.primitivemobs.entity.passive.EntityGroveSprite)
  Entity ID: 5625
  Entity Name: Grove Sprite
  Entity's Exact location: 139.50, 69.00, 249.50
  Entity's Block location: World: (139,69,249), Chunk: (at 11,4,9 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Entity's Momentum: -0.04, -0.08, -0.04
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: ~~ERROR~~ ReportedException: Saving entity NBT

**Comment by BugmanBugman** [comment]
Yeah this is pretty common, I had to disable them. I hope davey looks at it soon.
