### ISSUE TITLE
Thrown Egg Entity Crash on World Join

### ISSUE THREAD

**Issue by Snorps** [Daveyx0/PrimitiveMobs#282]
Keep getting this when I try to join my world with Primitive Mobs installed. Didn't touch any configs or mods between launches, and don't remember throwing any eggs before saving.

```---- Minecraft Crash Report ----
// There are four lights!

Time: 2020-01-21 12:12:09 GMT
Description: Ticking entity

java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Unknown Source)
    at net.daveyx0.primitivemobs.entity.item.EntityPrimitiveThrowable.onImpact(EntityPrimitiveThrowable.java:80)
    at net.minecraft.entity.projectile.EntityThrowable.onUpdate(EntityThrowable.java:249)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zbc000(World.java:4118)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: primitivemobs:primitive_egg (net.daveyx0.primitivemobs.entity.item.EntityPrimitiveThrowable)
  Entity ID: 2071
  Entity Name: entity.primitivemobs.primitive_egg.name
  Entity's Exact location: 916.94, 48.01, -557.95
  Entity's Block location: World: (916,48,-558), Chunk: (at 4,3,2 in 57,-35; contains blocks 912,0,-560 to 927,255,-545), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
  Entity's Momentum: 0.00, -0.15, -0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {Motion:[1.3000741967124673E-8d,-0.15000001446217945d,-1.6085536032650493E-8d],ForgeData:{},shake:0b,xTile:-1,UUIDLeast:-6479937513499806160L,RelativeAABB:[-0.125d,0.0d,-0.125d,0.125d,0.25d,0.125d],inGround:0b,Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[141.05396f,-89.999855f],UpdateBlocked:0b,FallDistance:0.0f,inTile:"minecraft:air",UUIDMost:-7359072009821927753L,ownerName:"Snorpy",Pos:[916.9411432374828d,48.01077191736615d,-557.9543199200563d],zTile:-1,Fire:0s,yTile:-1,ForgeCaps:{"llibrary:extendedentitydatacapability":{}}}

-- Affected level --
  Level name: testes
  All players: 1 total; [EntityPlayerMP['Snorpy'/1718, l='testes', x=882.65, y=63.00, z=-485.83]]
  Chunk stats: ServerChunkCache: 348 Drop: 0
  Level seed: -8485275456088839089
  Level generator: ID 06 - OTG, ver 0. Features enabled: true
  Level generator options: OpenTerrainGenerator
  Level spawn location: World: (875,63,-500), Chunk: (at 11,3,12 in 54,-32; contains blocks 864,0,-512 to 879,255,-497), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
  Level time: 28418 game time, 28418 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 4619 (now: true), thunder time: 1183 (now: true)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_144, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1918021200 bytes (1829 MB) / 3580362752 bytes (3414 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 112 mods loaded, 112 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                    | Version                     | Source                                           | Signature                                |
       |:------ |:--------------------- |:--------------------------- |:------------------------------------------------ |:---------------------------------------- |
       | LCHIJA | minecraft             | 1.12.2                      | minecraft.jar                                    | None                                     |
       | LCHIJA | mcp                   | 9.42                        | minecraft.jar                                    | None                                     |
       | LCHIJA | FML                   | 8.0.99.99                   | forge-1.12.2-14.23.5.2838-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                 | 14.23.5.2838                | forge-1.12.2-14.23.5.2838-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | otgcore               | 1.12.2 - v8.3               | minecraft.jar                                    | None                                     |
       | LCHIJA | bnbgamingcore         | 0.11.0                      | minecraft.jar                                    | None                                     |
       | LCHIJA | foamfixcore           | 7.7.4                       | minecraft.jar                                    | None                                     |
       | LCHIJA | dsurroundcore         | 3.5.4.3                     | minecraft.jar                                    | None                                     |
       | LCHIJA | randompatches         | 1.12.2-1.17.2.1             | randompatches-1.12.2-1.17.2.1.jar                | None                                     |
       | LCHIJA | additionalenderblocks | 2.1                         | AdditionalEnderBlocks-2.1.jar                    | None                                     |
       | LCHIJA | antiqueatlas          | 4.5.1                       | antiqueatlas-1.12.2-4.5.1.jar                    | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHIJA | antiqueatlasoverlay   | 1.2                         | antiqueatlas-1.12.2-4.5.1.jar                    | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHIJA | baubles               | 1.5.2                       | Baubles-1.12-1.5.2 (2).jar                       | None                                     |
       | LCHIJA | crafttweaker          | 4.1.19                      | CraftTweaker2-1.12-4.1.19.jar                    | None                                     |
       | LCHIJA | astralsorcery         | 1.10.20                     | astralsorcery-1.12.2-1.10.20.jar                 | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCHIJA | charset               | 0.5.6.2                     | Charset-Lib-0.5.6.2.jar                          | None                                     |
       | LCHIJA | mtlib                 | 3.0.6                       | MTLib-3.0.6.jar                                  | None                                     |
       | LCHIJA | modtweaker            | 4.0.17                      | modtweaker-4.0.17.jar                            | None                                     |
       | LCHIJA | jei                   | 4.15.0.287                  | jei_1.12.2-4.15.0.287.jar                        | None                                     |
       | LCHIJA | quark                 | r1.6-177                    | Quark-r1.6-177.jar                               | None                                     |
       | LCHIJA | autoreglib            | 1.3-32                      | AutoRegLib-1.3-32.jar                            | None                                     |
       | LCHIJA | base                  | 3.13.0                      | base-1.12.2-3.13.0.jar                           | None                                     |
       | LCHIJA | betteradvancements    | 0.1.0.77                    | BetterAdvancements-1.12.2-0.1.0.77.jar           | None                                     |
       | LCHIJA | openterraingenerator  | v8.3                        | OpenTerrainGenerator-1.12.2+-+v8.3.jar           | None                                     |
       | LCHIJA | biomebundle           | 5.1                         | Biome_Bundle-1.12.2-v6.1 (4).jar                 | None                                     |
       | LCHIJA | bnbgaminglib          | 2.17.6                      | BNBGamingLib-1.12.2-2.17.6.jar                   | None                                     |
       | LCHIJA | bubble_elevator       | 1.0-1.12.2                  | BubbleColumnElevator-1.0-1.12.2.jar              | None                                     |
       | LCHIJA | chameleon             | 1.12-4.1.3                  | Chameleon-1.12-4.1.3.jar                         | None                                     |
       | LCHIJA | sandro                | 1.2d                        | Redstone++ ver1.2d.jar                           | None                                     |
       | LCHIJA | redstoneplusplus      | 1.2d                        | Redstone++ ver1.2d.jar                           | None                                     |
       | LCHIJA | charm                 | 1.12.2-1.2.2                | Charm-1.12.2-1.2.2.jar                           | None                                     |
       | LCHIJA | clarity               | 1.1                         | clarity-1.1.jar                                  | None                                     |
       | LCHIJA | clumps                | 3.1.2                       | Clumps-3.1.2.jar                                 | None                                     |
       | LCHIJA | comforts              | 1.4.1.2                     | comforts-1.12.2-1.4.1.2.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | concreteplus          | 1.1.2                       | ConcreteExtends-1.1.2_1.12.jar                   | None                                     |
       | LCHIJA | contenttweaker        | 1.12.2-4.9.1                | ContentTweaker-1.12.2-4.9.1.jar                  | None                                     |
       | LCHIJA | controlling           | 3.0.8                       | Controlling-3.0.8.jar                            | None                                     |
       | LCHIJA | coralreef             | 2.0                         | CoralReef-2.5-1.12.2.jar                         | None                                     |
       | LCHIJA | configmod             | v1.0                        | coroutil-1.12.1-1.2.36.jar                       | None                                     |
       | LCHIJA | extendedrenderer      | v1.0                        | coroutil-1.12.1-1.2.36.jar                       | None                                     |
       | LCHIJA | coroutil              | 1.12.1-1.2.36               | coroutil-1.12.1-1.2.36.jar                       | None                                     |
       | LCHIJA | wearablebackpacks     | 3.1.4                       | WearableBackpacks-1.12.2-3.1.4.jar               | None                                     |
       | LCHIJA | corpsecomplex         | 1.0.8                       | corpsecomplex-1.12.2-1.0.8.jar                   | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | cosmeticbeds          | 1.12.2-1.0.2.2              | cosmeticbeds-1.12.2-1.0.2.2.jar                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | ctgui                 | 1.0.0                       | CraftTweaker2-1.12-4.1.19.jar                    | None                                     |
       | LCHIJA | crafttweakerjei       | 2.0.3                       | CraftTweaker2-1.12-4.1.19.jar                    | None                                     |
       | LCHIJA | diethopper            | 1.1                         | diethopper-1.1.jar                               | None                                     |
       | LCHIJA | earthworks            | 1.3.4.3                     | Earthworks-1.12-1.3.6.jar                        | None                                     |
       | LCHIJA | embers                | 1.12                        | EmbersRekindled-1.12.jar                         | None                                     |
       | LCHIJA | epicsiegemod          | 13.165                      | EpicSiegeMod-13.165.jar                          | None                                     |
       | LCHIJA | erosion               | 2.2.1                       | Erosion-2.2.1.jar                                | None                                     |
       | LCHIJA | extraalchemy          | 0.3.8.6.1-release           | extraalchemy-0.3.8.6.1-release.jar               | None                                     |
       | LCHIJA | familiarfauna         | 1.0.11                      | FamiliarFauna-1.12.2-1.0.11.jar                  | None                                     |
       | LCHIJA | fastleafdecay         | v14                         | FastLeafDecay-v14.jar                            | None                                     |
       | LCHIJA | fastbench             | 1.7.2                       | FastWorkbench-1.12.2-1.7.2.jar                   | None                                     |
       | LCHIJA | foamfix               | 0.10.5-1.12.2               | foamfix-0.10.5-1.12.2.jar                        | None                                     |
       | LCHIJA | fw                    | 1.6.0                       | FullscreenWindowed-1.12-1.6.0.jar                | None                                     |
       | LCHIJA | minecraftfuture       | 0.1.9                       | future-mc-0.1.9b.jar                             | None                                     |
       | LCHIJA | hardcoredarkness      | 2.0                         | HardcoreDarkness-MC1.12.2-2.0.jar                | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | hatstands             | 1.0.0                       | hatstands-1.0.0-1.12.2.jar                       | None                                     |
       | LCHIJA | hw_inv                | 1.12.1-1.1.13               | hostileworlds_invasions-1.12.1-1.1.13.jar        | None                                     |
       | LCHIJA | llibrary              | 1.7.19                      | llibrary-1.7.19-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire            | 1.8.3                       | iceandfire-1.8.3.jar                             | None                                     |
       | LCHIJA | ido                   | 1.0.4                       | ido-1.12.2-1.0.4.jar                             | None                                     |
       | LCHIJA | incontrol             | 3.9.16                      | incontrol-1.12-3.9.16.jar                        | None                                     |
       | LCHIJA | mantle                | 1.12-1.3.3.55               | Mantle-1.12-1.3.3.55.jar                         | None                                     |
       | LCHIJA | inspirations          | 1.12.2-0.2.7                | Inspirations-1.12.2-0.2.7.jar                    | None                                     |
       | LCHIJA | itemzoom              | 1.11                        | itemzoom_1.12.2-1.11.jar                         | None                                     |
       | LCHIJA | jaff                  | 1.7_for_1.12                | JustAFewFish-1.7_for_1.12.jar                    | None                                     |
       | LCHIJA | lex                   | 1.0.8                       | LibEx-1.12.2-1.0.8.jar                           | None                                     |
       | LCHIJA | lttweaker             | 1.1.14                      | LootTableTweaker-1.12.2-1.1.14.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | modnametooltip        | 1.10.1                      | modnametooltip_1.12.2-1.10.1.jar                 | None                                     |
       | LCHIJA | mousetweaks           | 2.10                        | MouseTweaks-2.10-mc1.12.2.jar                    | None                                     |
       | LCHIJA | mowziesmobs           | 1.5.4                       | mowziesmobs-1.5.4.jar                            | None                                     |
       | LCHIJA | multimob              | 1.0.5                       | multimob-1.0.5.jar                               | None                                     |
       | LCHIJA | netherchest           | 1.1.1                       | netherchest-1.1.1.jar                            | None                                     |
       | LCHIJA | nex                   | 2.0.8                       | NetherEx-1.12.2-2.0.8.jar                        | None                                     |
       | LCHIJA | notenoughcats         | 1.2.1                       | NotEnoughCats-1.12.2-1.2.1.jar                   | None                                     |
       | LCHIJA | notenoughscaffold     | 1.8                         | NotEnoughScaffold-1.12.2-1.8.jar                 | None                                     |
       | LCHIJA | nutrition             | 4.4.0                       | Nutrition-1.12.2-4.4.0.jar                       | None                                     |
       | LCHIJA | samsocean             | 1.0.2                       | OceanFloor-1.12.2-1.0.2.jar                      | None                                     |
       | LCHIJA | rustic                | 1.1.2                       | rustic-1.1.2.jar                                 | None                                     |
       | LCHIJA | ore_stone_variants    | 4.3                         | ore_stone_variants-4.4.jar                       | None                                     |
       | LCHIJA | plated                | 0.1.0                       | Plated-0.1.0.jar                                 | None                                     |
       | LCHIJA | primitivemobs         | 1.2.3a                      | primitivemobs-1.2.3a.jar                         | None                                     |
       | LCHIJA | quarkoddities         | 1                           | QuarkOddities-1.12.2.jar                         | None                                     |
       | LCHIJA | redstonepcb           | 0.1                         | RedstonePCB-0.1.jar                              | None                                     |
       | LCHIJA | resourceloader        | 1.5.3                       | ResourceLoader-MC1.12.1-1.5.3.jar                | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | sereneseasons         | 1.2.18                      | SereneSeasons-1.12.2-1.2.18-universal.jar        | None                                     |
       | LCHIJA | simplifiedhorses      | 1.2.1                       | SimplifiedHorses-v1.2.1-1.11.jar                 | None                                     |
       | LCHIJA | sit                   | v1.3                        | sit-1.12.2-v1.3.jar                              | None                                     |
       | LCHIJA | soundfilters          | 0.11_for_1.12               | SoundFilters-0.11_for_1.12.jar                   | None                                     |
       | LCHIJA | stg                   | 1.12.2-1.2.3                | stg-1.12.2-1.2.3.jar                             | None                                     |
       | LCHIJA | storagedrawers        | 1.12-5.3.5                  | StorageDrawers-1.12.2-5.3.8.jar                  | None                                     |
       | LCHIJA | stygian               | 1.0.4                       | stygian-1.0.4.jar                                | None                                     |
       | LCHIJA | tellme                | 0.7.0-dev.20190610.165828   | tellme-1.12.2-0.7.0-dev.20190610.165828.jar      | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCHIJA | tetra                 | 0.39.1                      | tetra-1.12.2-0.39.1.jar                          | None                                     |
       | LCHIJA | tips                  | 1.0.7                       | Tips-1.12.2-1.0.7.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | triumph               | 3.17.0                      | Triumph-1.12.2-3.17.0.jar                        | None                                     |
       | LCHIJA | unmending             | GRADLE:VERSION-GRADLE:BUILD | Unmending-1.0-2.jar                              | None                                     |
       | LCHIJA | vanillafix            | 1.0.10-SNAPSHOT             | VanillaFix-1.0.10-99.jar                         | None                                     |
       | LCHIJA | wards                 | 1.3.1                       | wards-1.3.1.jar                                  | None                                     |
       | LCHIJA | worldprimer           | 0.6.0-dev.20190525.121747   | worldprimer-1.12.2-0.6.0-dev.20190525.121747.jar | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCHIJA | worleycaves           | 1.4.1                       | worleycaves-1.4.1.jar                            | None                                     |
       | LCHIJA | orelib                | 3.5.2.2                     | OreLib-1.12.2-3.5.2.2.jar                        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround             | 3.5.4.3                     | DynamicSurroundings-1.12.2-3.5.4.3.jar           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | ladylib               | 2.1                         | Ladylib-2.1.jar                                  | None                                     |
       | LCHIJA | lumen                 | 0.4.0                       | lumen-Beta 0.4.1.jar                             | None                                     |
       | LCHIJA | phosphor-lighting     | 1.12.2-0.2.6                | phosphor-1.12.2-0.2.6+build50-universal.jar      | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | reauth                | 3.6.0                       | reauth-3.6.0.jar                                 | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | LCHIJA | snowrealmagic         | 0.3.2                       | SnowRealMagic-0.3.2.jar                          | None                                     |
       | LCHIJA | trapexpansion         | 1.0.0                       | trapexpansion-1.0.0.jar                          | None                                     |
  Loaded coremods (and transformers): CharmLoadingPlugin (Charm-1.12.2-1.2.2.jar)
                                        svenhjol.charm.base.CharmClassTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      BedPatch (bedpatch-2.2-1.12.2.jar)
                                        com.mordenkainen.bedpatch.BedPatchASM
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      iceandfire (iceandfire-1.8.3.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      RandomPatches (randompatches-1.12.2-1.17.2.1.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      AstralCore (astralsorcery-1.12.2-1.10.20.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      Snow! Real Magic! Core Mod (SnowRealMagic-0.3.2-coremod.jar)
                                        snownee.snow.asm.ASMTransformer
                                      BNBGamingCore (BNBGamingCore-1.12.2-0.11.0.jar)
                                        com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCoreClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
                                        org.orecruncher.dsurround.asm.Transformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
  Suspected Mods: Primitive Mobs (primitivemobs)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Snorpy'/1718, l='testes', x=882.65, y=63.00, z=-485.83]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 4```

**Comment by Snorps** [comment]
Fixed by removing primitive mobs, joining the world, adding primitive mobs, and then joining the world again.

Dunno what doing that might've messed up though lol

**Comment by Daveyx0** [comment]
Thanks! Not sure either but I built in a safety check.
