### ISSUE TITLE
[1.12.2] ServerHangWatchdog kills the server when entering nether

### ISSUE THREAD

**Issue by 346184** [Daveyx0/PrimitiveMobs#286]
In our 1.12.2 server using `forge-14.23.5.2847` when entering the Nether, the server crashes with the following stacktrace:

```
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2020-03-11 00:30:09 CET
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 120.00 seconds (should be max 0.05)
    at java.util.Spliterators$IteratorSpliterator.estimateSize(Spliterators.java:1822)
    at java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:497)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
    at net.daveyx0.primitivemobs.core.PrimitiveMobsEvents$EntityEventHandler.spawnEvent(PrimitiveMobsEvents.java:122)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_824_EntityEventHandler_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.world.World.spawnEntity(World.java:1209)
    at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:1058)
    at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:160)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:203)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by Daveyx0** [comment]
You probably figured this out a long time ago; but I googled it and it seems you need to increase a max server tick setting somewhere. I have not seen this personally before and sadly the stacktrace gives too little information for me to hunt it.
