### ISSUE TITLE
Crash game

### ISSUE THREAD

**Issue by nfww** [Daveyx0/PrimitiveMobs#303]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 9/8/20 1:41 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Primitive Mobs (primitivemobs)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/daveyx0/primitivemobs/entity/monster/EntityMimic
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:578)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/daveyx0/primitivemobs/entity/monster/EntityMimic
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:81)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 37 more
Caused by: java.lang.ClassNotFoundException: net.daveyx0.primitivemobs.entity.monster.EntityMimic
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 43 more
Caused by: java.lang.NoClassDefFoundError: net/daveyx0/multimob/entity/IMultiMob
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more
Caused by: java.lang.ClassNotFoundException: net.daveyx0.multimob.entity.IMultiMob
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 49 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 51 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (arm) version 3.10.84-perf-g7f0277a
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK Client VM (mixed mode), Oracle Corporation
	Memory: 76238192 bytes (72 MB) / 219299840 bytes (209 MB) up to 709558272 bytes (676 MB)
	JVM Flags: 2 total; -Xmx700m -Xms128m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 Optifine OptiFine_1.12.2_HD_U_F5 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version         | Source                          | Signature                                |
	|:----- |:------------- |:--------------- |:------------------------------- |:---------------------------------------- |
	| UC    | minecraft     | 1.12.2          | minecraft.jar                   | None                                     |
	| UC    | mcp           | 9.42            | minecraft.jar                   | None                                     |
	| UC    | FML           | 8.0.99.99       | forge-1.12.2-14.23.3.2655.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge         | 14.23.3.2655    | forge-1.12.2-14.23.3.2655.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | fpsreducer    | mc1.12.2-1.12.2 | FpsReducer1.12.2 AjGamingPH.jar | None                                     |
	| UC    | multimob      | 1.0.3           | multimob-1.0.3.jar              | None                                     |
	| UE    | primitivemobs | 1.2.3a          | primitivemobs-1.2.3a.jar        | None                                     |
	| UC    | thesummoner   | 1.0.1-beta      | thesummoner-1.0.1.jar           | None                                     |

	Loaded coremods (and transformers): 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 3
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 6

**Comment by Daveyx0** [comment]
It somehow cannot find EntityMimic.class? which is rather odd as that definitely should be simply included on both sides... .you did not mess with the mod files, did you?

**Comment by nfww** [comment]
I didnt mess up with ur mod

Pada tanggal 13 Sep 2020 6.19 PM, "Davey" <notifications@github.com>
menulis:
