### ISSUE TITLE
Crash with worldtypes which has unlimited height (CubicChunks)

### ISSUE THREAD

**Issue by roboderpy** [Daveyx0/PrimitiveMobs#83]
```
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner.getRandomChunkPosition(PrimitiveMobsWorldSpawner.java:164)
	at net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner.doCustomSpawning(PrimitiveMobsWorldSpawner.java:92)
	at net.daveyx0.primitivemobs.event.PrimitiveMobsSpawnerEventHandler.onWorldTickEvent(PrimitiveMobsSpawnerEventHandler.java:34)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_800_PrimitiveMobsSpawnerEventHandler_onWorldTickEvent_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:286)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Daveyx0** [comment]
If vanilla spawns work then technically CubicChunks should now work with PrimitiveMobs as well.
