### ISSUE TITLE
Client crash on /summon groveSprite

### ISSUE THREAD

**Issue by Braffolk** [Daveyx0/PrimitiveMobs#87]
I'm playing on a deticated server. When I used /summon groveSprite, the client crashed but the server did not.

I can't rejoin either before the mob is killed through console.

Playing on 1.1.16 beta

```
[B#360]  java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
[B#360]  	at com.google.common.base.Absent.get(Absent.java:45)
[B#360]  	at net.daveyx0.primitivemobs.entity.passive.EntityGroveSprite.getLeaves(EntityGroveSprite.java:249)
[B#360]  	at net.daveyx0.primitivemobs.entity.passive.EntityGroveSprite.func_70636_d(EntityGroveSprite.java:152)
[B#360]  	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
[B#360]  	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
[B#360]  	at net.minecraft.world.World.func_72866_a(World.java:1990)
[B#360]  	at net.minecraft.world.World.func_72870_g(World.java:1952)
[B#360]  	at net.minecraft.world.World.func_72939_s(World.java:1756)
[B#360]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
[B#360]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
[B#360]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
[B#360]  	at net.minecraft.client.main.Main.main(SourceFile:123)
[B#360]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#360]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#360]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#360]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#360]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#360]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Daveyx0** [comment]
Thanks for reporting. Sorry for the late response. Will check

**Comment by Daveyx0** [comment]
Will be fixed in next version
